# Generated by Django 3.1.7 on 2021-03-14 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='extendexd_user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(db_column='user_profile', upload_to='userprofiles', verbose_name='User Image')),
                ('linked_user', models.OneToOneField(db_column='linked_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Extended users',
                'db_table': 'extended_user',
            },
            managers=[
                ('extended_user', django.db.models.manager.Manager()),
            ],
        ),
    ]
