# Generated by Django 3.1.7 on 2021-03-15 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210315_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendexd_user_model',
            name='linked_user',
            field=models.OneToOneField(db_column='linked_user', on_delete=django.db.models.deletion.CASCADE, related_name='linked_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
