# Generated by Django 3.1.7 on 2021-03-16 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.validatator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20210315_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='enter_todo_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(db_column='Title', max_length=100, validators=[home.validatator.valid_data], verbose_name='Name')),
                ('datetime_to_happen', models.DateTimeField(db_column='date_to_happen', verbose_name='Date')),
                ('descriptions', models.TextField(db_column='discription', validators=[home.validatator.valid_data], verbose_name='Description')),
                ('isdone', models.BooleanField(default=False, verbose_name='Completed')),
                ('linked_profile', models.ForeignKey(db_column='linked_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Select user')),
            ],
        ),
    ]
