# Generated by Django 3.1.7 on 2021-03-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210316_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enter_todo_items',
            options={'verbose_name_plural': 'Todo_entries'},
        ),
        migrations.AlterField(
            model_name='enter_todo_items',
            name='descriptions',
            field=models.SlugField(db_column='discription', verbose_name='Description'),
        ),
    ]
