# Generated by Django 3.1.7 on 2021-03-17 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20210316_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter_todo_items',
            name='linked_profile',
            field=models.ForeignKey(db_column='linked_user', on_delete=django.db.models.deletion.CASCADE, related_name='connected_user', to=settings.AUTH_USER_MODEL, verbose_name='Select user'),
        ),
    ]
